agent.gamma: choice(0.5, 0.7, 0.9, 0.95, 0.99)
agent.learning_rate: tag(log, interval(1e-5, 1.))
agent.batch_size: choice(8, 16, 32, 64, 128)
agent.buffer_size: choice(1e4, 1e5, 1e6)
agent.tau: choice(0.0001, 0.001, 0.005, 0.01, 0.05, 0.1)
agent.train_freq: choice(1, 4, 8, 16, 32, 64)
agent.gradient_steps: choice(1, 4, 8, 16, 32, 64)
agent.noise_type: choice("ornstein-uhlenbeck", "normal")
agent.noise_std: interval(0.01,0.5)
agent.net_arch: choice("s","m","l")
agent.activation: choice("tanh", "relu")