agent.gamma: choice(0.5, 0.7, 0.9, 0.95, 0.99, 1.)
agent.learning_rate: tag(log, interval(1e-5, 1e-2))
agent.n_steps: choice(60, 180, 300, 600)
agent.batch_size: choice(8, 16, 32, 64, 128)
agent.n_epochs: choice(4, 8, 16, 32)
agent.ent_coef: tag(log, interval(1e-5, 1e-2))
agent.clip_range: choice(0.1, 0.2, 0.4, 0.6, 0.8)
agent.gae_lambda: choice(0.5, 0.7, 0.9, 0.95, 1.)
agent.max_grad_norm: choice(0.3, 0.5, 0.7, 0.9, 1, 2, 5)
agent.vf_coef: interval(0., 0.9)
agent.net_arch: choice("s","m","l")
agent.activation: choice("tanh", "leaky_relu")