trained_agent_path: ''
policy: "MlpPolicy"
learning_algo: "ddpg"
gamma: 1.
learning_rate: 1e-3
batch_size: 32
buffer_size: 1e5
tau: 0.005
train_freq: 1
gradient_steps: 8
noise_type: "normal"
noise_std: 0.001
net_arch: "m"
activation: "relu"